from selenium.webdriver.common.by import By

class AuthLocators:
    AUTH_PHONE = (By.ID, "username")
    AUTH_EMAIL = (By.ID, "username")
    AUTH_PASS = (By.ID, "password")
    AUTH_BTN = (By.ID, "kc-login")
    REG_LINK = (By.ID, "kc-register")
    PHONE_TAB_ELEMENT = (By.ID, "t-btn-tab-phone")
    MAIL_TAB_ELEMENT = (By.ID, "t-btn-tab-mail")
    LOGIN_TAB_ELEMENT = (By.ID, "t-btn-tab-login")
    LS_TAB_ELEMENT = (By.ID, "t-btn-tab-ls")
    LOGO_ELEMENT = (By.CSS_SELECTOR, "#page-left > div > div.what-is-container__logo-container > svg")
    INFO_ELEMENT = (By.CSS_SELECTOR, "#page-left > div > div.what-is")
    FORGOT_PASSW = (By.ID, "forgot_password")
    ERROR_AUTH = (By.ID, "form-error-message")
    CAPTCHA_ELEMENT = (By.CSS_SELECTOR, "#page-right > div > div > div > form > div.rt-captcha.reset-form__captcha > div.rt-captcha__left > div.rt-captcha__image-con > img")
    RESET_BTN = (By.ID, "reset")
    RESET_BACK = (By.ID, "reset-back")
    REG_FIRSTNAME = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div > div > div > input")
    REG_LASTNAME = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div > div:nth-of-type(2) > div > input")
    REG_ADDRESS = (By.ID, "address")
    REG_REGION = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div:nth-of-type(2) > div > div > input")
    REG_PASSW_CONFIRM = (By.ID, "password-confirm")
    REG_LINK_CONFIDENTAL = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div:nth-of-type(5) > a")
    REG_LOGO = (By.CSS_SELECTOR, "header#app-header > div > div > svg")
    REG_BTN = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > button")
    CONFIRM_EMAIL = (By.CSS_SELECTOR, "section#page-right > div > div > h1")
    REG_ERROR_NAME = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div > div > span")
    REG_ERROR_LASTNAME = (By.CSS_SELECTOR, "#page-right > div > div > div > form > div.name-container > div:nth-child(2) > span")
    REG_DIFF_PASSW = (By.CSS_SELECTOR, "#page-right > div > div > div > form > div.new-password-container > "
                                           "div.rt-input-container.rt-input-container--error.new-password-container__confirmed-password > span")
    REG_WRONG_PASSW = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div:nth-of-type(4) > div > span")
    REG_EXIST_MAIL = (By.CSS_SELECTOR, "#page-right > div > div > div > form > div.base-modal-wrapper.card-modal > div > div > h2")
    VK_BTN = (By.ID, "oidc_vk")
    ODN_BTN = (By.ID, 'oidc_ok')
    MAIL_BTN = (By.ID, 'oidc_mail')
    YA_BTN = (By.ID, 'oidc_ya')
    VK_PAGE = (By.XPATH, '#root > div > div > div > div > div.vkc__AuthRoot__root.vkuiSplitLayout__inner > div.vkc__AuthRoot__col.vkc__AuthRoot__contentCol.vkuiSplitCol > div > div > div > form > div:nth-child(1) > div > h1 > div')
    MAIL_PAGE = (By.XPATH, '#wrp > div.content > h1')
    ODN_PAGE = (By.XPATH, '#widget-el > div.ext-widget_h > div')
    YANDEX_PAGE = (By.XPATH, '#root > div > div.passp-page > div.passp-flex-wrapper > div > div > div.passp-auth-content > div:nth-child(3) > div > div > div > form > div > div.Phone-head.layout_head > h1')